networks:
  default:
    driver: 'bridge'

volumes:
  pg_data:
  passport_backend_config:

services:
  postgres:
    container_name: 'passport-backend-database'
    image: 'postgres:15.3'
    environment:
      - 'POSTGRES_PASSWORD=passport_backend'
      - 'POSTGRES_USER=passport_backend'
      - 'POSTGRES_DB=passport_backend'
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'

  passport-backend:
    container_name: 'passport-backend'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    depends_on:
      - 'postgres'
    ports:
      - '8080:8080'
    volumes:
      - 'passport_backend_config:/app/config'
    networks:
      - 'default'
